# Generated by Django 5.1.6 on 2025-02-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0001_initial'),
        ('users', '0002_alter_users_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='project',
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('Task Created', 'Task Created'), ('Task Updated', 'Task Updated'), ('Project Created', 'Project Created'), ('Epic Created', 'Epic Created'), ('Objective Created', 'Objective Created'), ('OKR Created', 'OKR Created'), ('Activity Created', 'Activity Created')], default='Task Created', max_length=255),
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='users.users')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='okrs.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='okrs.epic'),
        ),
        migrations.AddField(
            model_name='objective',
            name='epic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okrs.epic'),
            preserve_default=False,
        ),
    ]
