# Generated by Django 5.1.6 on 2025-02-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0002_remove_objective_project_alter_log_log_type_epic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='okr',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
    ]
