# Generated by Django 5.1.2 on 2025-05-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0004_alter_epic_options_alter_okr_options_okr_tasks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
