# Generated by Django 5.1.2 on 2025-05-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0005_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tipo',
            field=models.CharField(choices=[('mision', 'Misión'), ('proyecto', 'Proyecto')], default='mision', max_length=20),
        ),
    ]
