# Generated by Django 5.1.2 on 2025-05-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0006_project_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okrs.project'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='okrs.epic'),
        ),
    ]
