# Generated by Django 5.1.6 on 2025-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0007_objective_project_alter_objective_epic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20),
        ),
    ]
